"""create closing_reports/closing_menu_items

Revision ID: 700c2bee002f
Revises: 7f6bbd75a0d1
Create Date: 2025-07-16 23:17:55.197806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700c2bee002f'
down_revision: Union[str, Sequence[str], None] = '7f6bbd75a0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closing_reports',
    sa.Column('comp_cd', sa.String(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('today_sales', sa.Integer(), nullable=True),
    sa.Column('last_week_sales', sa.Integer(), nullable=True),
    sa.Column('emp_cnt', sa.Integer(), nullable=True),
    sa.Column('tb_cnt', sa.Integer(), nullable=True),
    sa.Column('tb_detail', sa.Text(), nullable=True),
    sa.Column('rmrk', sa.Text(), nullable=True),
    sa.Column('wait_note', sa.Text(), nullable=True),
    sa.Column('pd_amt', sa.String(), nullable=True),
    sa.Column('crdt', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('comp_cd', 'close_date')
    )
    op.create_table('closing_menu_items',
    sa.Column('comp_cd', sa.String(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('menu_name', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('crdt', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['comp_cd', 'close_date'], ['closing_reports.comp_cd', 'closing_reports.close_date'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comp_cd', 'close_date', 'menu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('closing_menu_items')
    op.drop_table('closing_reports')
    # ### end Alembic commands ###
